### ISSUE TITLE
Обсуждение: Новая коллекция - рандеву для WCF

### ISSUE THREAD

**Issue by mayorovp** [HellBrick/AsyncCollections#20]
Пытаюсь тут сделать новый транспорт для WCF - и мне понадобилась коллекция. В принципе, BufferBlock все еще подходит - но постоянные catch как-то напрягают. А OutputAvailableAsync().Result и вовсе дурно пахнет.

Есть ли мысли как проще реализовать коллекцию со следующими характеристиками?

1. Размер буфера - 0 (работа в режиме рандеву)
2. Поддержка 1 производителя и любого числа потребителей
3. Наличие как синхронных, так и асинхронных методов чтения
4. Метод "дождаться наличия значения"
5. Передача маркера конца потока от производителя к потребителям

**Comment by HellBrick** [comment]
Привет. Можешь чуть подробнее раскрыть идею? В частности:

1. За тем чтобы producer-ов было не более одного следит кто-то снаружи или это на совести коллекции?
2. Про жизнь без буфера: я правильно понимаю, что запись по сути асинхронная и завершается когда кто-то новый айтем забрал?
3. Маркер конца потока - это что-то в духе `BlockingCollection.CompleteAdding()`, сигнал всем что айтемов больше не будет?
4. Нужна ли отмена записи/чтения?

**Comment by mayorovp** [comment]
1. Это сценарий использования, обусловленный особенностями WCF. Т.е. если это что-нибудь упрощает - реализация коллекции может рассчитывать на данное свойство.
2. Да, так же как и чтение завершается когда итем кто-то положил. Это и называется "рандеву".
3. Оно самое.
4. Отмена чтения - нужна, там в WCF тайм-аут на каждую операцию. Отмена записи - не обязательна, но в таком случае понадобится что-то типа вызова `CompleteTaking()`.

**Comment by mayorovp** [comment]
Нашел класс AsyncProducerConsumerQueue из пакета Nito.AsyncEx - но там нет синхронного метода OutputAvailable. Кроме того, вроде бы пакет AsyncEx имеет проблемы с рекурсией в нагруженных проектах.

Нашел также класс AsyncProducerConsumerQueue из пакета Nito.AsyncEx.Coordination - но там нет вызова TryReceive (!).

**Comment by HellBrick** [comment]
На первый взгляд самым простым способом кажется использовать немного модифицированную `AsyncQueue`.

1. Асинхронность записи реализуется легко: айтем, пришедший раньше соответствующего consumer-а, хранится на as is, а заворачивается в аналогичную consumer-ам структуру (`TaskCompletionSource`, `CancellationToken.Register()`, всё такое). И соответственно пришедший после этого consumer должен этот таск завершить - по сути возникает полная симметрия между добавлением айтема и добавлением consumer-а.

2. `CompleteAdding()` навернуть вроде не проблема. С запросами, случающимися после вызова `CompleteAdding()` всё просто: при вызове взводим отдельный флаг, который дальше при записи/чтении все читают `VolatileRead`-ом и отваливаются. Чуть веселее с запросами, которые пришли до/во время `CompleteAdding()`. На ум приходит воспользоваться уже готовым функционалом по отмене чего угодно: завести отдельный `CancellationToken` для остановки очереди и при чтении/записи использовать делать `CancellationTokenSource.CreateLinkedTokenSource( _completeAddingToken, requestToken ).Token` и дальше работать с ним. По `CompleteAdding()` дёргаем токен и наблюдаем как все таски разрешаются сами собой: кто успел, завершится параллельно пришедшим айтемом/consumer-ом, остальные отменятся. Отдельная прелесть в том, что этот кусок функционала вообще легко делается поверх любой реализации коллекции, без залезания внутрь.

3. `OutputAvailable` вроде втыкается довольно очевидным образом.

4. Синхронное чтение - это что-то в духе `bool TryTake( out T )`? Такая штука вроде делается легко: это то же самое основное асинхронное чтение, только если мы пришли, когда айтема ещё нет, вместо складывания consumer-а в очередь возвращаем false.

Получается решение, которое на самом деле поддерживает многопоточное добавление. При желании можно выкинуть очередь айтемов, т.к. он гарантированно один, но по-моему это не сильно упрощает код, так что я бы забил.

**Comment by HellBrick** [comment]
Если пойдёшь таким путём, возможно стоит посмотреть на реализацию `AsyncQueue` из ветки future - она там потенциально более оптимальная. Но пока не обкатанная в бою, так что на свой страх и риск =)

**Comment by mayorovp** [comment]
> Синхронное чтение - это что-то в духе bool TryTake( out T )? Такая штука
вроде делается легко: это то же самое основное асинхронное чтение, только
если мы пришли, когда айтема ещё нет, вместо складывания consumer-а в
очередь возвращаем false.

Нет, речь идет о блокирующем синхронном чтении.

3 ноября 2016 г., 16:28 пользователь HellBrick <notifications@github.com>
написал:

**Comment by HellBrick** [comment]
`TakeAsync().GetAwaiter().GetResult()`? =) Я не думаю, что в primarily асинхронной коллекции можно сделать что-то более адекватное для синхронного сценария.
