### ISSUE TITLE
WithThreadAbortedFlag() doesn't work on Mono

### ISSUE THREAD

**Issue by HellBrick** [HellBrick/AsyncCollections#4]

**Comment by mayorovp** [comment]
Хм, а что этот флаг вообще делал?..

**Comment by HellBrick** [comment]
Не давал continuation-у `TakeAsync()` инлайниться в том же потоке, в котором выполняется метод `Add()`. Как показала практика, инлайнинг в этом месте абсолютнейше неочевиден и приносит больше вреда, чем пользы.

**Comment by HellBrick** [comment]
(На самом деле это грязный хак в ожидании `TaskCreationOptions.RunContinuationsAsynchronously` из 4.6)

**Comment by mayorovp** [comment]
Хм, а в чем был вред от синхронного вызова?..

**Comment by mayorovp** [comment]
https://github.com/HellBrick/AsyncCollections/pull/5

**Comment by HellBrick** [comment]
Типичный сценарий использования: один поток закидывает задачи в очередь и несколько потоков что-то с этими задачами делают. Логично предположить, что `Add()` отрабатывает мгновенно, но, если перед этим другие потоки сделали `TakeAsync()` по пустой коллекции, то метод `Add()` не завершится, пока забравший первую задачу поток не дойдёт до следующего `await`, до которого легко может быть какая-нибудь тяжёлая логика. На практике это приводит к тому, что после каждого `await TakeAsync()` нужно в обязательном порядке делать `await Task.Yield()`, иначе о параллельной обработке элементов очереди можно забыть.

Эту неинтуитивную жесть было решено исправить внесением аналога `await Task.Yield()` внутрь `TakeAsync()`. Возможно, потом стоит добавить свойство, позволяющее вернуть старое поведение - мало ли какие кейсы бывают - но по дефолту инлайниться тут не стоит.

**Comment by mayorovp** [comment]
Да, понял, согласен - Add должен в общем случае отрабатывать быстро.

**Comment by mayorovp** [comment]
Привык я работать с установленным планировщиком задач - вот и не понял, в чем вообще дело :)
